name: Advanced Ontology Review

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run advanced review
        run: python scripts/advanced_review.py
      - name: Commit and push results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update ontology metadata [skip ci]'
          branch: ${{ github.ref }}
          file_pattern: docs/ontologies.json
